---
- hosts: all
  gather_facts: no
  become: true
  become_method: su
  tasks:
    - name: Установка требуемых пакетов
      yum:
        name: ['emacs', 'gcc', 'make', 'texlive', 'nasm', 'qemu-system-x86']
        state: latest
        use_backend: yum3
